# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/whisper_normalizer',
                'doc_host': 'https://kurianbenoy.github.io',
                'git_url': 'https://github.com/kurianbenoy/whisper_normalizer',
                'lib_path': 'whisper_normalizer'},
  'syms': {'whisper_normalizer.core': {'whisper_normalizer.core.foo': ('core.html#foo', 'whisper_normalizer/core.py')}}}
