# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_international.ipynb.

# %% auto #0
__all__ = ['NUM2WORDS_SUPPORTED_LANGS', 'FrenchTextNormalizer', 'SpanishTextNormalizer', 'ArabicTextNormalizer',
           'ChineseTextNormalizer', 'RussianTextNormalizer']

# %% ../nbs/02_international.ipynb #international
import re
import unicodedata

import regex
from text_to_num import alpha2digit


# Language codes num2words ships a converter for. Hardcoded (rather than
# introspected from the installed package) so capability declarations don't
# change depending on whether the optional [tts] extra happens to be present.
NUM2WORDS_SUPPORTED_LANGS = frozenset({
    "am", "ar", "az", "be", "bn", "ca", "ce", "cs", "cy", "da", "de", "en",
    "eo", "es", "fa", "fi", "fr", "he", "hu", "id", "is", "it", "ja", "kn",
    "ko", "kz", "lt", "lv", "nl", "no", "pl", "pt", "ro", "ru", "sk", "sl",
    "sr", "sv", "te", "tet", "tg", "th", "tr", "uk", "vi",
})


def _num2words_module():
    try:
        import num2words as nw
    except ImportError:
        raise ImportError(
            "tts_mode requires the 'num2words' package: "
            "pip install 'whisper_normalizer[tts]'"
        ) from None
    return nw


def _validate_tts_lang(lang: str) -> None:
    """Raise if ``lang`` can't be used with tts_mode; imports num2words as a side effect."""
    _num2words_module()
    if lang not in NUM2WORDS_SUPPORTED_LANGS:
        raise ValueError(
            f"tts_mode is not supported for language {lang!r}: num2words has no converter for it"
        )


def _digits_to_words(text: str, lang: str) -> str:
    """Convert digit sequences (including decimals) to words using num2words."""
    nw = _num2words_module()

    def replace_num(m: re.Match) -> str:
        raw = m.group(0)
        try:
            value = float(raw) if "." in raw else int(raw)
            return nw.num2words(value, lang=lang)
        except Exception:
            return raw

    # Match a whole numeric token, including an optional decimal part, so
    # "1234.56" converts as one number instead of "1234" and "56" separately.
    return re.sub(r"\b\d+(?:\.\d+)?\b", replace_num, text)


class _LatinTextNormalizer:
    """Shared conservative normalization for space-separated Latin-script languages."""

    language: str
    number_threshold = 0

    def __init__(self, tts_mode: bool = False):
        if tts_mode:
            _validate_tts_lang(self.language)
        self.tts_mode = tts_mode

    def _normalize_numeric_separators(self, text: str) -> str:
        return text

    def _preprocess(self, text: str) -> str:
        return text

    def __call__(self, text: str) -> str:
        # NFC retains meaningful accents while making canonically equivalent text comparable.
        text = unicodedata.normalize("NFC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.translate(str.maketrans({"\u2019": "'", "`": "'", "\u2010": "-", "\u2013": "-", "\u2014": "-"}))
        text = text.replace("\u200b", "").replace("\ufeff", "")
        if self.tts_mode:
            # Merge thousands separators and normalize the decimal mark first, so a
            # grouped/decimal number converts as one value instead of several.
            text = _digits_to_words(self._normalize_numeric_separators(text), self.language)
        else:
            text = alpha2digit(self._preprocess(text), self.language, threshold=self.number_threshold)
            text = self._normalize_numeric_separators(text)
        # Punctuation is a word boundary for Whisper-style comparison; accents remain intact.
        text = regex.sub(r"(?<!\d)[\p{P}\p{S}]+|[\p{P}\p{S}]+(?!\d)", " ", text)
        return re.sub(r"\s+", " ", text).strip()


class FrenchTextNormalizer(_LatinTextNormalizer):
    """Normalize French text without removing accents or ligatures."""

    language = "fr"

    def _normalize_numeric_separators(self, text: str) -> str:
        # French commonly groups thousands with a regular, no-break, or narrow no-break space.
        text = re.sub(r"(?<=\d)[ \u00a0\u202f](?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)


class SpanishTextNormalizer(_LatinTextNormalizer):
    """Normalize Spanish text without removing accents, dieresis, or enye."""

    language = "es"
    # Avoid treating the common articles un and una as numeric expressions.
    number_threshold = 2

    def _preprocess(self, text: str) -> str:
        return re.sub("\\bveinti\\u00fan\\b", "veintiuno", text)

    def _normalize_numeric_separators(self, text: str) -> str:
        # In Spanish, dots group thousands and commas separate decimal fractions.
        text = re.sub(r"(?<=\d)\.(?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)


# %% ../nbs/02_international.ipynb #non-latin-normalizers
class _NonLatinTextNormalizer:
    """Shared punctuation and whitespace cleanup for non-Latin scripts."""

    language: str = ""

    def __init__(self, tts_mode: bool = False):
        if tts_mode:
            _validate_tts_lang(self.language)
        self.tts_mode = tts_mode

    def _prepare(self, text: str) -> str:
        return text

    def __call__(self, text: str) -> str:
        text = unicodedata.normalize("NFKC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.replace("\u200b", "").replace("\ufeff", "")
        text = self._prepare(text)
        if self.tts_mode and self.language:
            text = _digits_to_words(text, self.language)
        text = regex.sub(r"(?<!\d)[\p{P}\p{S}]+|[\p{P}\p{S}]+(?!\d)", " ", text)
        return re.sub(r"\s+", " ", text).strip()


class ArabicTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Arabic orthographic variants, diacritics, digits, and punctuation."""

    language = "ar"
    _digits = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")

    def _prepare(self, text: str) -> str:
        text = text.translate(self._digits)
        text = re.sub(r"[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]", "", text)
        text = text.replace("ـ", "")
        text = text.translate(str.maketrans({"أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ؤ": "و", "ئ": "ي", "ى": "ي"}))
        text = re.sub(r"(?<=\d)٬(?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d)[،٫](?=\d)", ".", text)


class ChineseTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Chinese punctuation, whitespace, and common written numerals."""

    language = "zh"
    _numerals = {"零": 0, "〇": 0, "一": 1, "二": 2, "两": 2, "三": 3, "四": 4, "五": 5, "六": 6, "七": 7, "八": 8, "九": 9}
    _units = {"十": 10, "百": 100, "千": 1000, "万": 10000, "亿": 100000000}

    @classmethod
    def _number(cls, match: re.Match) -> str:
        value = match.group()
        if not any(char in cls._units for char in value):
            return "".join(str(cls._numerals[char]) for char in value)
        total = section = digit = 0
        last_large_unit = 1
        for char in value:
            if char in cls._numerals:
                digit = cls._numerals[char]
            else:
                unit = cls._units[char]
                if unit >= 10000:
                    section += digit
                    if not section and not total:
                        section = 1
                    if unit > last_large_unit:
                        total = (total + section) * unit
                    else:
                        total += section * unit
                    section = digit = 0
                    last_large_unit = unit
                else:
                    section += (digit or 1) * unit
                    digit = 0
        return str(total + section + digit)

    def __call__(self, text: str) -> str:
        text = super().__call__(text)
        if not self.tts_mode:
            # In TTS mode, Chinese numerals are already spoken form; skip digit conversion.
            text = re.sub(r"[零〇一二两三四五六七八九十百千万亿]+", self._number, text)
        return re.sub(r"\s+", "", text)


class RussianTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Russian case, the optional letter ``ё``, and numeric separators."""

    language = "ru"

    def _prepare(self, text: str) -> str:
        text = text.replace("ё", "е")
        text = re.sub(r"(?<=\d)[ \u00a0\u202f](?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)

