# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_international.ipynb.

# %% auto #0
__all__ = ['FrenchTextNormalizer', 'SpanishTextNormalizer']

# %% ../nbs/02_international.ipynb #international
import re
import unicodedata

import regex
from text_to_num import alpha2digit


class _LatinTextNormalizer:
    """Shared conservative normalization for space-separated Latin-script languages."""

    language: str

    def _normalize_numeric_separators(self, text: str) -> str:
        return text

    def _preprocess(self, text: str) -> str:
        return text

    def __call__(self, text: str) -> str:
        # NFC retains meaningful accents while making canonically equivalent text comparable.
        text = unicodedata.normalize("NFC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.translate(str.maketrans({"\u2019": "'", "`": "'", "\u2010": "-", "\u2013": "-", "\u2014": "-"}))
        text = text.replace("\u200b", "").replace("\ufeff", "")
        text = alpha2digit(self._preprocess(text), self.language, threshold=0)
        text = self._normalize_numeric_separators(text)
        # Punctuation is a word boundary for Whisper-style comparison; accents remain intact.
        text = regex.sub(r"(?<!\d)[\p{P}\p{S}]+|[\p{P}\p{S}]+(?!\d)", " ", text)
        return re.sub(r"\s+", " ", text).strip()


class FrenchTextNormalizer(_LatinTextNormalizer):
    """Normalize French text without removing accents or ligatures."""

    language = "fr"

    def _normalize_numeric_separators(self, text: str) -> str:
        # French commonly groups thousands with a regular, no-break, or narrow no-break space.
        text = re.sub(r"(?<=\d)[ \u00a0\u202f](?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)


class SpanishTextNormalizer(_LatinTextNormalizer):
    """Normalize Spanish text without removing accents, dieresis, or enye."""

    language = "es"

    def _preprocess(self, text: str) -> str:
        return re.sub("\\bveinti\\u00fan\\b", "veintiuno", text)

    def _normalize_numeric_separators(self, text: str) -> str:
        # In Spanish, dots group thousands and commas separate decimal fractions.
        text = re.sub(r"(?<=\d)\.(?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)


