# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_international.ipynb.

# %% auto #0
__all__ = ['FrenchTextNormalizer', 'SpanishTextNormalizer', 'ArabicTextNormalizer', 'ChineseTextNormalizer',
           'RussianTextNormalizer']

# %% ../nbs/02_international.ipynb #international
import re
import unicodedata

import regex
from text_to_num import alpha2digit


class _LatinTextNormalizer:
    """Shared conservative normalization for space-separated Latin-script languages."""

    language: str
    number_threshold = 0

    def _normalize_numeric_separators(self, text: str) -> str:
        return text

    def _preprocess(self, text: str) -> str:
        return text

    def __call__(self, text: str) -> str:
        # NFC retains meaningful accents while making canonically equivalent text comparable.
        text = unicodedata.normalize("NFC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.translate(str.maketrans({"\u2019": "'", "`": "'", "\u2010": "-", "\u2013": "-", "\u2014": "-"}))
        text = text.replace("\u200b", "").replace("\ufeff", "")
        text = alpha2digit(self._preprocess(text), self.language, threshold=self.number_threshold)
        text = self._normalize_numeric_separators(text)
        # Punctuation is a word boundary for Whisper-style comparison; accents remain intact.
        text = regex.sub(r"(?<!\d)[\p{P}\p{S}]+|[\p{P}\p{S}]+(?!\d)", " ", text)
        return re.sub(r"\s+", " ", text).strip()


class FrenchTextNormalizer(_LatinTextNormalizer):
    """Normalize French text without removing accents or ligatures."""

    language = "fr"

    def _normalize_numeric_separators(self, text: str) -> str:
        # French commonly groups thousands with a regular, no-break, or narrow no-break space.
        text = re.sub(r"(?<=\d)[ \u00a0\u202f](?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)


class SpanishTextNormalizer(_LatinTextNormalizer):
    """Normalize Spanish text without removing accents, dieresis, or enye."""

    language = "es"
    # Avoid treating the common articles un and una as numeric expressions.
    number_threshold = 2

    def _preprocess(self, text: str) -> str:
        return re.sub("\\bveinti\\u00fan\\b", "veintiuno", text)

    def _normalize_numeric_separators(self, text: str) -> str:
        # In Spanish, dots group thousands and commas separate decimal fractions.
        text = re.sub(r"(?<=\d)\.(?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)



# %% ../nbs/02_international.ipynb #non-latin-normalizers
class _NonLatinTextNormalizer:
    """Shared punctuation and whitespace cleanup for non-Latin scripts."""

    def _prepare(self, text: str) -> str:
        return text

    def __call__(self, text: str) -> str:
        text = unicodedata.normalize("NFKC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.replace("\u200b", "").replace("\ufeff", "")
        text = self._prepare(text)
        text = regex.sub(r"(?<!\d)[\p{P}\p{S}]+|[\p{P}\p{S}]+(?!\d)", " ", text)
        return re.sub(r"\s+", " ", text).strip()


class ArabicTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Arabic orthographic variants, diacritics, digits, and punctuation."""

    _digits = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")

    def _prepare(self, text: str) -> str:
        text = text.translate(self._digits)
        text = re.sub(r"[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]", "", text)
        text = text.replace("ـ", "")
        text = text.translate(str.maketrans({"أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ؤ": "و", "ئ": "ي", "ى": "ي"}))
        text = re.sub(r"(?<=\d)٬(?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d)[،٫](?=\d)", ".", text)


class ChineseTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Chinese punctuation, whitespace, and common written numerals."""

    _numerals = {"零": 0, "〇": 0, "一": 1, "二": 2, "两": 2, "三": 3, "四": 4, "五": 5, "六": 6, "七": 7, "八": 8, "九": 9}
    _units = {"十": 10, "百": 100, "千": 1000, "万": 10000, "亿": 100000000}

    @classmethod
    def _number(cls, match: re.Match) -> str:
        value = match.group()
        if not any(char in cls._units for char in value):
            return "".join(str(cls._numerals[char]) for char in value)
        total = section = digit = 0
        last_large_unit = 1
        for char in value:
            if char in cls._numerals:
                digit = cls._numerals[char]
            else:
                unit = cls._units[char]
                if unit >= 10000:
                    section += digit
                    if not section and not total:
                        section = 1
                    if unit > last_large_unit:
                        total = (total + section) * unit
                    else:
                        total += section * unit
                    section = digit = 0
                    last_large_unit = unit
                else:
                    section += (digit or 1) * unit
                    digit = 0
        return str(total + section + digit)

    def __call__(self, text: str) -> str:
        text = super().__call__(text)
        text = re.sub(r"[零〇一二两三四五六七八九十百千万亿]+", self._number, text)
        return re.sub(r"\s+", "", text)


class RussianTextNormalizer(_NonLatinTextNormalizer):
    """Normalize Russian case, the optional letter ``ё``, and numeric separators."""

    def _prepare(self, text: str) -> str:
        text = text.replace("ё", "е")
        text = re.sub(r"(?<=\d)[ \u00a0\u202f](?=\d{3}(?:\D|$))", "", text)
        return re.sub(r"(?<=\d),(?=\d)", ".", text)

