"""Docs: https://kurianbenoy.github.io/whisper_normalizer/multilingual.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_multilingual.ipynb.

# %% auto #0
__all__ = ['LANGUAGE_REGISTRY', 'LANGUAGE_ALIASES', 'MultilingualTextNormalizer', 'LanguageSupport', 'get_normalizer',
           'supported_languages']

# %% ../nbs/03_multilingual.ipynb #exports
import functools
import inspect
from dataclasses import dataclass
from typing import Callable
import re
import unicodedata

import regex

from .english import EnglishTextNormalizer
from whisper_normalizer.indic import (
    BengaliNormalizer,
    DevanagariNormalizer,
    GujaratiNormalizer,
    HindiNormalizer,
    KannadaNormalizer,
    MalayalamNormalizer,
    OdiaNormalizer,
    PunjabiNormalizer,
    TamilNormalizer,
    TeluguNormalizer,
)
from whisper_normalizer.international import (
    ArabicTextNormalizer,
    ChineseTextNormalizer,
    FrenchTextNormalizer,
    RussianTextNormalizer,
    SpanishTextNormalizer,
)


class MultilingualTextNormalizer:
    """Conservative, script-safe normalization for languages without bespoke rules."""

    def __call__(self, text: str) -> str:
        text = unicodedata.normalize("NFC", text).lower()
        text = re.sub(r"[<\[][^>\]]*[>\]]", "", text)
        text = re.sub(r"\(([^)]+?)\)", "", text)
        text = text.replace("​", "").replace("﻿", "")
        # Preserve Unicode marks: they carry meaning in scripts such as Arabic.
        text = regex.sub(r"[\p{P}\p{S}]+", " ", text)
        return re.sub(r"\s+", " ", text).strip()


@dataclass(frozen=True)
class LanguageSupport:
    """A supported language and the normalization level available for it.

    ``tier`` is one of:

    - ``"dedicated"``: a normalizer written and reviewed for this language.
    - ``"script"``: no dedicated class yet, but the language shares a script
      with a dedicated normalizer that is reused as-is (for example Marathi
      reuses the Devanagari normalizer, without Hindi's number/TTS tuning).
    - ``"generic"``: only conservative, script-safe cleanup is applied; no
      language-specific rules exist.
    """

    code: str
    name: str
    factory: Callable[..., Callable[[str], str]]
    capabilities: tuple[str, ...]
    tier: str


_GENERIC_CAPABILITIES = ("unicode", "punctuation", "whitespace", "case")


# Coverage matches the ~99 languages Whisper itself documents (openai/whisper
# whisper/tokenizer.py LANGUAGES, checked against release 20250625), plus
# Odia, which is not one of Whisper's languages but already has a dedicated,
# reviewed normalizer in this package.
LANGUAGE_REGISTRY = {
    "ar": LanguageSupport("ar", "Arabic", ArabicTextNormalizer, ('unicode', 'punctuation', 'numbers', 'digits'), "dedicated"),
    "bn": LanguageSupport("bn", "Bengali", BengaliNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "en": LanguageSupport("en", "English", EnglishTextNormalizer, ('unicode', 'punctuation', 'numbers', 'spelling'), "dedicated"),
    "es": LanguageSupport("es", "Spanish", SpanishTextNormalizer, ('unicode', 'punctuation', 'numbers', 'locale_numbers'), "dedicated"),
    "fr": LanguageSupport("fr", "French", FrenchTextNormalizer, ('unicode', 'punctuation', 'numbers', 'locale_numbers'), "dedicated"),
    "gu": LanguageSupport("gu", "Gujarati", GujaratiNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "hi": LanguageSupport("hi", "Hindi", HindiNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "kn": LanguageSupport("kn", "Kannada", KannadaNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "ml": LanguageSupport("ml", "Malayalam", MalayalamNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "or": LanguageSupport("or", "Odia", OdiaNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "pa": LanguageSupport("pa", "Punjabi", PunjabiNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "ru": LanguageSupport("ru", "Russian", RussianTextNormalizer, ('unicode', 'punctuation', 'numbers', 'locale_numbers'), "dedicated"),
    "ta": LanguageSupport("ta", "Tamil", TamilNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "te": LanguageSupport("te", "Telugu", TeluguNormalizer, ('unicode', 'script', 'numbers', 'tts_mode'), "dedicated"),
    "zh": LanguageSupport("zh", "Chinese", ChineseTextNormalizer, ('unicode', 'punctuation', 'numbers', 'whitespace'), "dedicated"),
    "as": LanguageSupport("as", "Assamese", functools.partial(BengaliNormalizer, lang="as", do_remap_assamese_chars=True), ('unicode', 'script'), "script"),
    "mr": LanguageSupport("mr", "Marathi", functools.partial(DevanagariNormalizer, lang="mr"), ('unicode', 'script'), "script"),
    "ne": LanguageSupport("ne", "Nepali", functools.partial(DevanagariNormalizer, lang="ne"), ('unicode', 'script'), "script"),
    "sa": LanguageSupport("sa", "Sanskrit", functools.partial(DevanagariNormalizer, lang="sa"), ('unicode', 'script'), "script"),
    "af": LanguageSupport("af", "Afrikaans", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "am": LanguageSupport("am", "Amharic", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "az": LanguageSupport("az", "Azerbaijani", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ba": LanguageSupport("ba", "Bashkir", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "be": LanguageSupport("be", "Belarusian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "bg": LanguageSupport("bg", "Bulgarian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "bo": LanguageSupport("bo", "Tibetan", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "br": LanguageSupport("br", "Breton", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "bs": LanguageSupport("bs", "Bosnian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ca": LanguageSupport("ca", "Catalan", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "cs": LanguageSupport("cs", "Czech", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "cy": LanguageSupport("cy", "Welsh", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "da": LanguageSupport("da", "Danish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "de": LanguageSupport("de", "German", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "el": LanguageSupport("el", "Greek", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "et": LanguageSupport("et", "Estonian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "eu": LanguageSupport("eu", "Basque", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "fa": LanguageSupport("fa", "Persian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "fi": LanguageSupport("fi", "Finnish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "fo": LanguageSupport("fo", "Faroese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "gl": LanguageSupport("gl", "Galician", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ha": LanguageSupport("ha", "Hausa", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "haw": LanguageSupport("haw", "Hawaiian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "he": LanguageSupport("he", "Hebrew", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "hr": LanguageSupport("hr", "Croatian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ht": LanguageSupport("ht", "Haitian Creole", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "hu": LanguageSupport("hu", "Hungarian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "hy": LanguageSupport("hy", "Armenian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "id": LanguageSupport("id", "Indonesian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "is": LanguageSupport("is", "Icelandic", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "it": LanguageSupport("it", "Italian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ja": LanguageSupport("ja", "Japanese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "jw": LanguageSupport("jw", "Javanese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ka": LanguageSupport("ka", "Georgian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "kk": LanguageSupport("kk", "Kazakh", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "km": LanguageSupport("km", "Khmer", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ko": LanguageSupport("ko", "Korean", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "la": LanguageSupport("la", "Latin", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "lb": LanguageSupport("lb", "Luxembourgish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ln": LanguageSupport("ln", "Lingala", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "lo": LanguageSupport("lo", "Lao", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "lt": LanguageSupport("lt", "Lithuanian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "lv": LanguageSupport("lv", "Latvian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "mg": LanguageSupport("mg", "Malagasy", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "mi": LanguageSupport("mi", "Maori", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "mk": LanguageSupport("mk", "Macedonian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "mn": LanguageSupport("mn", "Mongolian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ms": LanguageSupport("ms", "Malay", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "mt": LanguageSupport("mt", "Maltese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "my": LanguageSupport("my", "Myanmar", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "nl": LanguageSupport("nl", "Dutch", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "nn": LanguageSupport("nn", "Nynorsk", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "no": LanguageSupport("no", "Norwegian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "oc": LanguageSupport("oc", "Occitan", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "pl": LanguageSupport("pl", "Polish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ps": LanguageSupport("ps", "Pashto", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "pt": LanguageSupport("pt", "Portuguese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ro": LanguageSupport("ro", "Romanian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sd": LanguageSupport("sd", "Sindhi", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "si": LanguageSupport("si", "Sinhala", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sk": LanguageSupport("sk", "Slovak", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sl": LanguageSupport("sl", "Slovenian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sn": LanguageSupport("sn", "Shona", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "so": LanguageSupport("so", "Somali", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sq": LanguageSupport("sq", "Albanian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sr": LanguageSupport("sr", "Serbian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "su": LanguageSupport("su", "Sundanese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sv": LanguageSupport("sv", "Swedish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "sw": LanguageSupport("sw", "Swahili", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "tg": LanguageSupport("tg", "Tajik", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "th": LanguageSupport("th", "Thai", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "tk": LanguageSupport("tk", "Turkmen", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "tl": LanguageSupport("tl", "Tagalog", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "tr": LanguageSupport("tr", "Turkish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "tt": LanguageSupport("tt", "Tatar", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "uk": LanguageSupport("uk", "Ukrainian", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "ur": LanguageSupport("ur", "Urdu", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "uz": LanguageSupport("uz", "Uzbek", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "vi": LanguageSupport("vi", "Vietnamese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "yi": LanguageSupport("yi", "Yiddish", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "yo": LanguageSupport("yo", "Yoruba", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
    "yue": LanguageSupport("yue", "Cantonese", MultilingualTextNormalizer, _GENERIC_CAPABILITIES, "generic"),
}

LANGUAGE_ALIASES = {
    "afrikaans": "af",
    "albanian": "sq",
    "amharic": "am",
    "arabic": "ar",
    "armenian": "hy",
    "assamese": "as",
    "azerbaijani": "az",
    "bashkir": "ba",
    "basque": "eu",
    "belarusian": "be",
    "bengali": "bn",
    "bosnian": "bs",
    "breton": "br",
    "bulgarian": "bg",
    "burmese": "my",
    "cantonese": "yue",
    "castilian": "es",
    "catalan": "ca",
    "chinese": "zh",
    "croatian": "hr",
    "czech": "cs",
    "danish": "da",
    "dutch": "nl",
    "english": "en",
    "estonian": "et",
    "faroese": "fo",
    "finnish": "fi",
    "flemish": "nl",
    "french": "fr",
    "galician": "gl",
    "georgian": "ka",
    "german": "de",
    "greek": "el",
    "gujarati": "gu",
    "haitian": "ht",
    "haitian creole": "ht",
    "hausa": "ha",
    "hawaiian": "haw",
    "hebrew": "he",
    "hindi": "hi",
    "hungarian": "hu",
    "icelandic": "is",
    "indonesian": "id",
    "italian": "it",
    "japanese": "ja",
    "javanese": "jw",
    "kannada": "kn",
    "kazakh": "kk",
    "khmer": "km",
    "korean": "ko",
    "lao": "lo",
    "latin": "la",
    "latvian": "lv",
    "letzeburgesch": "lb",
    "lingala": "ln",
    "lithuanian": "lt",
    "luxembourgish": "lb",
    "macedonian": "mk",
    "malagasy": "mg",
    "malay": "ms",
    "malayalam": "ml",
    "maltese": "mt",
    "mandarin": "zh",
    "maori": "mi",
    "marathi": "mr",
    "moldavian": "ro",
    "moldovan": "ro",
    "mongolian": "mn",
    "myanmar": "my",
    "nepali": "ne",
    "norwegian": "no",
    "nynorsk": "nn",
    "occitan": "oc",
    "od": "or",
    "odia": "or",
    "panjabi": "pa",
    "pashto": "ps",
    "persian": "fa",
    "polish": "pl",
    "portuguese": "pt",
    "punjabi": "pa",
    "pushto": "ps",
    "romanian": "ro",
    "russian": "ru",
    "sanskrit": "sa",
    "serbian": "sr",
    "shona": "sn",
    "sindhi": "sd",
    "sinhala": "si",
    "sinhalese": "si",
    "slovak": "sk",
    "slovenian": "sl",
    "somali": "so",
    "spanish": "es",
    "sundanese": "su",
    "swahili": "sw",
    "swedish": "sv",
    "tagalog": "tl",
    "tajik": "tg",
    "tamil": "ta",
    "tatar": "tt",
    "telugu": "te",
    "thai": "th",
    "tibetan": "bo",
    "turkish": "tr",
    "turkmen": "tk",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "valencian": "ca",
    "vietnamese": "vi",
    "welsh": "cy",
    "yiddish": "yi",
    "yoruba": "yo",
}


def _supports_option(factory: Callable[..., Callable[[str], str]], option: str) -> bool:
    """Return whether ``factory``'s constructor accepts a given keyword option."""
    try:
        parameters = inspect.signature(factory).parameters
    except (TypeError, ValueError):
        return False
    if option in parameters:
        return True
    return any(p.kind is inspect.Parameter.VAR_KEYWORD for p in parameters.values())


def get_normalizer(language: str, **options) -> Callable[[str], str]:
    """Return a fresh normalizer for a BCP-47 tag, ISO 639-1 code, or language name.

    ``language`` accepts plain codes (``"hi"``), BCP-47 tags with a region or
    script subtag (``"hi-IN"``, ``"zh-Hans"``, ``"es-ES"``), and English
    language names (``"hindi"``). Only the primary language subtag drives
    selection: a region/script suffix is accepted but does not currently
    change which normalizer is returned. Keyword options such as
    ``tts_mode=True`` are validated against the selected normalizer and raise
    ``ValueError`` if it doesn't accept them, instead of being silently
    ignored.
    """
    key = language.lower().replace("_", "-").split("-", 1)[0]
    key = LANGUAGE_ALIASES.get(key, key)
    entry = LANGUAGE_REGISTRY.get(key)
    if entry is None:
        supported = ", ".join(sorted(LANGUAGE_REGISTRY))
        raise ValueError(f"Unsupported language: {language!r}. Supported codes: {supported}")
    unsupported_options = sorted(name for name in options if not _supports_option(entry.factory, name))
    if unsupported_options:
        raise ValueError(
            f"{entry.name} normalizer does not support option(s): {', '.join(unsupported_options)}"
        )
    return entry.factory(**options)


def supported_languages() -> tuple[LanguageSupport, ...]:
    """Return the language registry in ISO-code order."""

    return tuple(LANGUAGE_REGISTRY[code] for code in sorted(LANGUAGE_REGISTRY))
